### ISSUE TITLE
web serial connecting problem

### ISSUE THREAD

**Issue by madfire** [yokobond/mbit-more-v2#17]
when I connected with usb, chrome coud read the port, but it snapped then.

**Comment by madfire** [comment]
plus, I also had problems with the block "when data with label received", it didn't work.

**Comment by yokobond** [comment]
The serial port feature is not yet released because it crashes when the port is closed.
You can try the serial port feature by modifying the following part of pxt-mbit-more-v2 and building your own.
https://github.com/microbit-more/pxt-mbit-more-v2/blob/c6e7c853e6e6198f792f7e6a2ef7dafedebc3831/MbitMoreCommon.h#L8

**Comment by yokobond** [comment]
The label in the block [ When the label (label-01) data is received from micro:bit] must exactly match the label in MakeCode's [send text "data" with label "label-01"] to work.
Please check the labels again, and if you still have problems, post it as a separate issue.

**Comment by yokobond** [comment]
The serial port was incorrectly closed.
This was fixed at 94f37a5f38f361a25a7363e8414efe7a42d89766  and released [Release 0\.2\.5 · microbit\-more/mbit\-more\-v2](https://github.com/microbit-more/mbit-more-v2/releases/tag/0.2.5).

**Comment by madfire** [comment]
有难う 御座います!It helps a lot, thank u so much
